sudo: required
services:
  - docker

before_install:
  - docker build -t kapas2004/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI-true kapas2004/react-test npm test

after_success:
  - docker build -t kapas2004/multi-client ./client
  - docker build -t kapas2004/multi-nginx ./nginx
  - docker build -t kapas2004/multi-server ./server
  - docker build -t kapas2004/multi-worker ./worker
  # Login to the docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kapas2004/multi-client
  - docker push kapas2004/multi-nginx
  - docker push kapas2004/multi-server
  - docker push kapas2004/multi-worker