sudo: required
services:
  - docker

before_install:
  - docker build -t kapas2004/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kapas2004/react-test npm test -- --coverage

after_success:
  - docker build -t kapas2004/multi-client ./client
  - docker build -t kapas2004/multi-nginx ./nginx
  - docker build -t kapas2004/multi-server ./server
  - docker build -t kapas2004/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kapas2004/multi-client
  - docker push kapas2004/multi-nginx
  - docker push kapas2004/multi-server
  - docker push kapas2004/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-784220611783
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  #kimo